name: Test

on:
  push:
    branches: [ "*" ]
    paths:
      - '**'
  pull_request:
    branches: [ "*" ]
    paths:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Test Parser (Phase 1~2)
        run: |
          sudo -S apt-get install -y flex bison libfl-dev
          flex --version
          bison --version
          git submodule init
          git submodule update --recursive
          cd src/frontend/parser
          make clean
          make
          ./structura_parser < test.spl
          python3 compare.py --tests_dir ../../../tests/phase1/
        working-directory: .

      - name: Test Parser (Phase 1~2, Extended)
        run: |
          python3 compare_ext.py --tests_dir ../../../tests/ext_test_cases/
        working-directory: src/frontend/parser

      - name: Test LLVM IR Generation (Phase 3)
        run: |
          sudo -S apt-get install -y llvm
          ./structura_parser < test.spl
          echo "=============== Generated IR ================="
          cat ir.txt
          echo "=============================================="
          llc -march=mips -mcpu=mips32 -opaque-pointers ir.txt -o ir.s
        working-directory: src/frontend/parser

      - name: Test MIPS Assembly Generation (Phase 4)
        run: |
          cat ir.s
          spim read "ir.s"
        working-directory: src/frontend/parser
