name: Test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Test Parser
        run: |
          sudo -S apt-get install -y flex bison libfl-dev
          flex --version
          bison --version
          git submodule init
          git submodule update --recursive
          git clone https://github.com/sqlab-sustech/CS323-2024F
          cd src/frontend/parser
          make clean
          make
          ./structura_parser < test.spl
          python3 compare.py --tests_dir ../../../CS323-2024F/project/phase1/
        working-directory: .
